### ISSUE TITLE
Plan for support multiple tfstate (like ecspresso)

### ISSUE THREAD

**Issue by yumafuu** [Songmu/ecschedule#70]
I wanna lookup multi tfstate files in pulgins secion.

like  ↓
```yaml
plugins:
   - name: tfstate
     config:
       url: s3://tfstate/first.tfstate
     func_prefix: first_
   - name: tfstate
     config:
       url: s3://tfstate/second.tfstate
     func_prefix: second_
```

May I implement it?
